name: Dockerizing the prediction app
on: 
    push:
        branches:
            - main

jobs:
    push_to_hub:
        name: Image to hub
        runs-on: ubuntu-latest
        
        steps:
            - name: to repo
              uses: actions/checkout@v3
              
           

            - name: upload to dockerr
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                docker build -t my_app_container .
                docker tag my_app_container ${{ secrets.DOCKER_USERNAME }}/my_app_container
                docker push ${{ secrets.DOCKER_USERNAME }}/my_app_container